### ISSUE TITLE
Create Accurate Labels

### ISSUE THREAD

**Issue by mustafagonul** [574BandOfBrothers/memoriae#12]
After the discussion in the classroom, I think we should create more accurate labels for our project. Creating label matrix would be better solution for our project. Every issue should be two labels, pointing phase and module.

**Comment by fatiharaci** [comment]
Actually I have no idea what label matrix but it could be good. Here are the labels i created:

homework
research
project management
tools

**Comment by metepinar** [comment]
May I suggest these labels so that multiple assignees to a single issue could have a better understanding of the current situation of that particular issue, or other issues in general? This enables us to communicate the ongoing work effort spent on each issue while issue is still open, so multiple parties could avoid starting to work on an issue that someone else has already been working on. This might prove useful in avoiding lost time because when an assignee starts working on an issue, there is no way of broadcasting that important event to others in the team. More assignees means, more time would be saved.

Status: Abandoned
Status: Accepted
Status: Available
Status: Blocked
Status: Completed
Status: In Progress
Status: On Hold
Status: Pending
Status: Review Needed
Status: Revision Needed

**Comment by ardaogulcan** [comment]
Following labels may be created right now, additional labels may be included as they needed.

**Feature**: Will be used for new features to the project
**Bugfix**: Will be used for bug fixes, this is for development environment bugfixes.
**Improvement**: Will be used for improvement tasks which are neither adds new features nor fixes a bug
**Hotfix**: Will be used for critical bugfixes to the production environment which may not wait regular release cycle.
**Task**: Will be used for tasks. It involves non code tasks.
**Story**: Will be used for bigger features which may contain multiple smaller features. All smaller features should be created separately and linked to a story if necessary.
**Epic**: Critical and big task which will effect multiple aspects of project. Epics can contain multiple stories and features.
**Test**: Will be used for test related issues
**Docs**: Will be used for documentation related issues
